name: 02 - Eventos
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *' # Ejecuta el workflow diariamente a medianoche (ajustable)
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: ShowTrigger
        run: |
          echo "Event name: ${{ github.event_name }}"